# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-13 06:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('adress', models.CharField(max_length=23)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23)),
                ('adress', models.CharField(max_length=25)),
                ('roll', models.IntegerField(default=8)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
