# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0004_auto_20181018_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='user',
            field=models.CharField(default='ab', max_length=23),
        ),
        migrations.AddField(
            model_name='sell',
            name='user',
            field=models.CharField(default='ab', max_length=23),
        ),
        migrations.AlterField(
            model_name='sell',
            name='product_details',
            field=models.CharField(max_length=500),
        ),
    ]
